# GPT Model Configuration File

# Model settings
model:
  output_dir: outputs
  save_name: gpt-model-wiki-2.pt
  device: null  # cpu, mps or cuda. If None, will select the best available one
  model_type: GPT_CONFIG_400M  

# Training configuration
training:
  test_train_ratio: 0.9  # Test vs Train split ratio
  num_epochs: 1  # Number of epochs (1, since the dataset is already huge)
  batch_size: 8  # Suggested 8 or less for local training, 16/32/64/128 for GPU
  subset_ratio: 0.001  # Percentage of original dataset to use (e.g., 0.1 = 10%)
  advanced_training: true  # Enables learning rate warmup, cosine decay and gradient clipping
  test_before_training: false  # If true, tests model before training (may take time)
  text_stride: 1024 # While creating input/target ids, we create sliding window chunks using strides, should be less than context_length


# Inference settings
inference:
  start_context: "Water is essential for all forms of life because"
  max_new_tokens: 50
  temperature: 0.7
  top_k: 50
  top_p: 0.9
  num_beams: 1 # Greater than 1 for decoding using sampling, otherwise its greedy. 
  early_stopping: true

# Model Architecture Configurations
model_configs: # 400M parameter configuration
  vocab_size: 50257   # Vocabulary size
  context_length: 1024 
  emb_dim: 1024       # Embedding dimension
  n_heads: 16        # Number of attention heads
  n_layers: 24       # Number of layers
  drop_rate: 0.1     # Dropout rate
  qkv_bias: true    # Query-key-value bias

  # Locally use batch size 1-2, but will take longer to train